### ISSUE TITLE
Failed to build bytesmith-0.3.14.0

### ISSUE THREAD

**Issue by paolo-mo** [byteverse/bytesmith#39]
Recent bytesmith update to 0.3.14.0 may have broken something as I have the error below with ghc 9.6.7 on Windows

Adding                    bytesmith <= 0.3.13.0,
to   build-depends: in a cabal file, fixes the issue the issues at the moment in a project using ip-1.7.8 which depends on this package.

Any help on this matter will be greatly appreciated. Thanks.

--------------------------------------------------------
Resolving dependencies...
Build profile: -w ghc-9.6.7 -O1
In order, the following will be built (use -v for more details):
 - bytesmith-0.3.14.0 (lib) (first run)
Configuring library for bytesmith-0.3.14.0...
Preprocessing library for bytesmith-0.3.14.0...
Building library for bytesmith-0.3.14.0...
[ 1 of 12] Compiling Data.Bytes.Parser.Internal ( src\Data\Bytes\Parser\Internal.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\Internal.o )
[ 2 of 12] Compiling Data.Bytes.Parser.Rebindable ( src\Data\Bytes\Parser\Rebindable.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\Rebindable.o )
[ 3 of 12] Compiling Data.Bytes.Parser.Types ( src\Data\Bytes\Parser\Types.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\Types.o )
[ 4 of 12] Compiling Data.Bytes.Parser.Unsafe ( src\Data\Bytes\Parser\Unsafe.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\Unsafe.o )
[ 5 of 12] Compiling Data.Bytes.Parser ( src\Data\Bytes\Parser.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser.o )
[ 6 of 12] Compiling Data.Bytes.Parser.LittleEndian ( src\Data\Bytes\Parser\LittleEndian.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\LittleEndian.o )

src\Data\Bytes\Parser\LittleEndian.hs:46:1: warning: [-Wunused-imports]
    The import of `Control.Applicative' is redundant
      except perhaps to import instances from `Control.Applicative'
    To import instances alone, use: import Control.Applicative()
   |
46 | import Control.Applicative (liftA2)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 7 of 12] Compiling Data.Bytes.Parser.Leb128 ( src\Data\Bytes\Parser\Leb128.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\Leb128.o )
[ 8 of 12] Compiling Data.Bytes.Parser.Latin ( src\Data\Bytes\Parser\Latin.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\Latin.o )
[ 9 of 12] Compiling Data.Bytes.Parser.BigEndian ( src\Data\Bytes\Parser\BigEndian.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\BigEndian.o )
[10 of 12] Compiling Data.Bytes.Parser.Base128 ( src\Data\Bytes\Parser\Base128.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\Base128.o )
[11 of 12] Compiling Data.Bytes.Parser.Ascii ( src\Data\Bytes\Parser\Ascii.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\Ascii.o )

src\Data\Bytes\Parser\Ascii.hs:115:21: error: [GHC-83865]
    * Couldn't match expected type `Data.Text.Array.Array'
                  with actual type `PM.ByteArray'
    * In the first argument of `Text', namely `arr'
      In the first argument of `pure', namely `(Text arr off len)'
      In the expression: pure (Text arr off len)
    |
115 |     then pure (Text arr off len)
    |                     ^^^
[12 of 12] Compiling Data.Bytes.Parser.Utf8 ( src\Data\Bytes\Parser\Utf8.hs, \bytesmith-0.3.14.0\dist-newstyle\build\x86_64-windows\ghc-9.6.7\bytesmith-0.3.14.0\build\Data\Bytes\Parser\Utf8.o )
Error: [Cabal-7125]
Failed to build bytesmith-0.3.14.0.

**Comment by kaol** [comment]
Looks like the culprit is with using `Text` data constructor from `Data.Text.Internal` to access its internals. The way bytesmith does it worked until `text-2.0.2` but the internals changed starting with 2.1.

**Comment by andrewthad** [comment]
Adding a hackage revision restricting `text` to versions less than 2.1 should fix this. I'll do that now.

Then I need to figure out how to actually fix it, and I can release a bytesmith-0.3.14.1 with that change.

**Comment by andrewthad** [comment]
I looked into this more, and I'm confused. The way bytesmith accesses text's internals works fine with `text-2.1`. (In fact, I think it's text-2.0 that it doesn't work with, but that's indicating in the cabal file already.) I just built it on my computer. Can you run `cabal freeze` and then paste the contents of the `cabal.project.freeze` file so I can see what version of `text` you are building with?

**Comment by kaol** [comment]
My bad. I looked at it a bit hastily and I got it the wrong way around. I'm at ghc 9.6 and it's got text 2.0.2 included and I didn't have an explicit versioned dependency on it and that's the text version I had then.

When I added `text >= 2.1` in my cabal I got bytesmith to compile.
