### PR TITLE
referencing the correct bytebuild

### PR DESCRIPTION
**Pull request by teto**
I have been trying to adapt this library for ghc9.2 but I am blocked against some errors:

```
Build profile: -w ghc-9.2.1 -O1
In order, the following will be built (use -v for more details):
 - bytesmith-0.3.8.0 (lib) (first run)
Preprocessing library for bytesmith-0.3.8.0..
Building library for bytesmith-0.3.8.0..
[ 5 of 12] Compiling Data.Bytes.Parser ( src/Data/Bytes/Parser.hs, /home/teto/mptcp/bytesmith/dist-newstyle/build/x86_64-linux/ghc-9.2.1/bytesmith-0.3.8.0/build/Data/Bytes/Parser.o, /home/teto/mptcp/bytesmith/dist-newstyle/build/x86_64-linux/ghc-9.2.1/bytesmith-0.3.8.0/build/Data/Bytes/Parser.dyn_o )

src/Data/Bytes/Parser.hs:222:11: error:
    • Couldn't match expected type ‘Exts.Word8#’
                  with actual type ‘Word#’
    • In the pattern: 0##
      In a case alternative: 0## -> (# s, (# | (# (), off, len #) #) #)
      In the expression:
        case Exts.indexWord8OffAddr# ptr 0# of
          0## -> (# s, (# | (# (), off, len #) #) #)
          c -> case len of
                 0# -> (# s, (# e | #) #)
                 _ -> case Exts.eqWord# c (Exts.indexWord8Array# arr off) of
                        1# -> ...
                        _ -> ...
    |
222 |           0## -> (# s, (# | (# (), off, len #) #) #)
    |           ^^^

src/Data/Bytes/Parser.hs:225:36: error:
    • Couldn't match expected type ‘Word#’
                  with actual type ‘Exts.Word8#’
    • In the first argument of ‘Exts.eqWord#’, namely ‘c’
      In the expression: Exts.eqWord# c (Exts.indexWord8Array# arr off)
      In the expression:
        case Exts.eqWord# c (Exts.indexWord8Array# arr off) of
          1# -> go (Exts.plusAddr# ptr 1#) (off +# 1#) (len -# 1#)
          _ -> (# s, (# e | #) #)
    |
225 |             _ -> case Exts.eqWord# c (Exts.indexWord8Array# arr off) of
    |                                    ^

src/Data/Bytes/Parser.hs:225:39: error:
    • Couldn't match expected type ‘Word#’
                  with actual type ‘Exts.Word8#’
    • In the second argument of ‘Exts.eqWord#’, namely
        ‘(Exts.indexWord8Array# arr off)’
      In the expression: Exts.eqWord# c (Exts.indexWord8Array# arr off)
      In the expression:
        case Exts.eqWord# c (Exts.indexWord8Array# arr off) of
          1# -> go (Exts.plusAddr# ptr 1#) (off +# 1#) (len -# 1#)
          _ -> (# s, (# e | #) #)
    |
225 |             _ -> case Exts.eqWord# c (Exts.indexWord8Array# arr off) of
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Bytes/Parser.hs:486:52: error:
    • Couldn't match expected type ‘Word#’
                  with actual type ‘Exts.Word32#’
    • In the expression: a
      In the expression: (# a, b, c #)
      In the expression: (# | (# a, b, c #) #)
    |
486 |       (# | (# W32# a, b, c #) #) -> (# s1, (# | (# a, b, c #) #) #)
    |                                                    ^

src/Data/Bytes/Parser.hs:507:52: error:
    • Couldn't match expected type ‘Exts.Word32#’
                  with actual type ‘Word#’
    • In the first argument of ‘W32#’, namely ‘a’
      In the expression: W32# a
      In the expression: (# W32# a, b, c #)
    |
507 |       (# | (# a, b, c #) #) -> (# s1, (# | (# W32# a, b, c #) #) #)
    |                                                    ^
    ```

### CODE REVIEW

**Comment by teto** [comment]
it builds now though I might have lost older versions :/

**Comment by prikhi** [comment]
Hey! @costarastrology is also trying to get this working on 9.2 so we can bring it(and, eventually, `ip`) into Stackage nightly.

To get `Rebindable` working in old GHCs you can do something like this:

```haskell
{-# LANGUAGE CPP #-}
-- ...
#if MIN_VERSION_base(4,16,0)
import GHC.Exts (LiftedRep)
#endif
-- ...
#if !MIN_VERSION_base(4,16,0)
type LiftedRep = 'LiftedRep
#endif
```

Also getting these errors in `Data.Bytes.Parser` (& `.Utf8` & `.Latin`) with ghc 9.0.2:
```
src/Data/Bytes/Parser.hs:486:52: error:
    Not in scope: ‘Exts.word32ToWord#’
    Module ‘GHC.Exts’ does not export ‘word32ToWord#’.
    |
486 |       (# | (# W32# a, b, c #) #) -> (# s1, (# | (# Exts.word32ToWord# a, b, c #) #) #)
    |                                                    ^^^^^^^^^^^^^^^^^^

src/Data/Bytes/Parser.hs:507:53: error:
    Not in scope: ‘Exts.wordToWord32#’
    Module ‘GHC.Exts’ does not export ‘wordToWord32#’.
    |
507 |       (# | (# a, b, c #) #) -> (# s1, (# | (# W32# (Exts.wordToWord32# a), b, c #) #) #)
    |                                                     ^^^^^^^^^^^^^^^^^^
```

One way around this is [`Basement.Compat.Primitive`](https://www.stackage.org/haddock/lts-19.3/basement-0.0.14/Basement-Compat-Primitive.html#v:word32ToWord-35-). Adding CPP conditionals to those 3 modules fixes builds & all tests pass with ghc 9.0.2:

```haskell
import qualified GHC.Exts as Exts
#if __GLASGOW_HASKELL__ < 902
import qualified Basement.Compat.Primitive as Exts
#endif
```
I verified this also works for stackage nightly, LTS 19, & LTS 18.

We could limit the scope of this w/ a simple Compat module(haven't actually tested this):

```haskell
{-# LANGUAGE CPP #-}
module Data.Bytes.Parser.Compat 
  ( module Exts
  ) where

import qualified GHC.Exts as Exts
#if __GLASGOW_HASKELL__ < 902
import qualified Basement.Compat.Primitive as Exts
#endif
```

If adding `CPP` or `basement` is a non-starter, we'll need to do something similar to the byteslice changes:
https://github.com/byteverse/byteslice/pull/18/files

File: cabal.project [hunk 1]
```diff
@@ -1,4 +1,6 @@
-packages: .
+packages:
+    .
+    ../bytebuild
```
Comment (prikhi) [inline cabal.project:3]: need to revert this change

File: bytesmith.cabal [hunk 2]
```diff
@@ -40,6 +40,7 @@ library
     , text-short >=0.1.3 && <0.2
     , run-st >=0.1 && <0.2
     , wide-word >=0.1.0.9 && <0.2
+    , ghc-prim
```
Comment (prikhi) [inline bytesmith.cabal:43]: Drop this, module docs say to import `GHC.Exts` instead of `GHC.Types`:
https://www.stackage.org/haddock/lts-19.3/ghc-prim-0.7.0/GHC-Types.html

**Comment by prikhi** [comment]
@andrewthad if you let me know which solution you prefer, I am down to make a PR based off of this one.

- CPP + Basement
- CPP + Basement + Compat module
- [byteslice style](https://github.com/byteverse/byteslice/pull/18/files) w/ additional `src-xyz` source dirs based on ghc version

**Comment by teto** [comment]
@prikhi thanks for taking over.

**Comment by prikhi** [comment]
@teto definitely don't mean to "butt in" and take over this, but Co-Star is happy to subsidize the work needed to get this & `ip` working with ghc 9.2 & stackage.

**Comment by teto** [comment]
actually I've spent so much time porting different stuff to ghc 9.2 already (for company and private use) that I will happily let someone take over

**Comment by teto** [comment]
@prikhi any news ?

**Comment by prikhi** [comment]
Hey, I was waiting for some direction on which of those 3 ways to handle this... I could just make a PR with a similar style to the byteslice upgrade. I'm away until June 9th though.

**Comment by andrewthad** [comment]
Why would we need to guard the import of `Basement.Compat.Primitive as Exts` with CPP? The purpose of `Compat` modules is typically to take on the burden of CPP so that consumers of the API are able to avoid writing CPP. I'm in favor of depending on `basement` since it's a very light dep.

**Comment by prikhi** [comment]
oh! looks like GHC 9.2 support was added in #23

**Comment by teto** [comment]
lets close this then
